#!/bin/bash

# Copy/paste this job script into a text file and submit with the command:
#    sbatch thefilename
# job standard output will go to the file slurm-%j.out (where %j is the job ID)

#SBATCH --time=00:15:00   # walltime limit (HH:MM:SS)
#SBATCH --nodes=1   # number of nodes
#SBATCH --ntasks-per-node=36   # 36 processor core(s) per node 
#SBATCH --partition=class-short    # class node(s)
#SBATCH --job-name="424-lect19"

# LOAD MODULES, INSERT CODE, AND RUN YOUR PROGRAMS HERE
./main.exe 1 0.00000000001
./main.exe 2 0.00000000001
./main.exe 4 0.00000000001
./main.exe 6 0.00000000001
./main.exe 8 0.00000000001
./main.exe 16 0.00000000001
./main.exe 32 0.00000000001